### ISSUE TITLE
support python 3

### ISSUE THREAD

**Issue by eyadsibai** [samuell/sciluigi#1]
it seems python 3 is not supported with the current code

**Comment by samuell** [comment]
@eyadsibai Thanks for reporting! Do you have any specific reports?

What I can think of is the use of the deprecated `commands` library. This is switched to use subprocess now. I hope to test this myself very shortly.

**Comment by jeffcjohnson** [comment]
I just panicked when I saw on the README that Python 3 wasn't supported but then this ticket gave me hope that it actually is.  You may want to remove the note on the README stating that Python 3 isn't supported :)

**Comment by samuell** [comment]
Thanks for pinging about this @jeffcjohnson ! Unfortunately, I realized there was more changes needed than I anticipated :P ... things like iterators and stuff ... I guess one would have to throw in a bit of the six library, to bridge over those 2/3 gaps.

Should be totally doable (luigi itself does it this way), but has to be done :)

**Comment by jeffcjohnson** [comment]
Yeah, I ran into that.  I'm working on a pull request right now :)

**Comment by samuell** [comment]
Awesome! :)

**Comment by samuell** [comment]
Fixed in 7ff5feced14cfe8da571ba988cd7c363185eb68b
