### ISSUE TITLE
Passing parameters to the workflow

### ISSUE THREAD

**Issue by hbredin** [samuell/sciluigi#16]
In the tutorial, `replacement` parameter for `MyFooReplacer`is hard-coded in the definition of the workflow:

```python
class MyWorkflow(sl.WorkflowTask):
    def workflow(self):
        # Initialize tasks:
        foowrt = self.new_task('foowriter', MyFooWriter)
        foorpl = self.new_task('fooreplacer', MyFooReplacer,
            replacement='bar')

        # Here we do the *magic*: Connecting outputs to inputs:
        foorpl.in_foo = foowrt.out_foo

        # Return the last task(s) in the workflow chain.
        return foorpl
```

Then, calling ```sciluigi.run_local(main_task_cls=MyWorkflow)``` will always replace `foo` by `bar`.
How can we pass a different value of `replacement` to the workflow?

Should I override `MyWorkflow.__init__()` with something like:

```python
class MyWorkflow(sl.WorkflowTask):
    def __init__(self, replacement='bar'):
        super(self, MyWorkflow).__init__()
        self.replacement = replacement
```

and then use `self.replacement` in place of `'bar'`?

**Comment by samuell** [comment]
Hi @hbredin, thanks for asking!

The `MyWorkflow` task is a normal luigi task at its core (although with extra stuff added by sciluigi), so you can add luigi parameters to it, and then just forward it to the tasks parameter with the same name, like so:

```python
class MyWorkflow(sl.WorkflowTask):
    replacement = luigi.Parameter()

    def workflow(self):
        # Initialize tasks:
        foowrt = self.new_task('foowriter', MyFooWriter)
        foorpl = self.new_task('fooreplacer', MyFooReplacer,
            replacement=self.replacement)

        # Here we do the *magic*: Connecting outputs to inputs:
        foorpl.in_foo = foowrt.out_foo

        # Return the last task(s) in the workflow chain.
        return foorpl

if __name__ == '__main__':
    sciluigi.run_local(main_task_cls=MyWorkflow)
```

And then, you would execute this with:
```bash
python sciluigitest.py --replacement=somethingelse
```

**Comment by samuell** [comment]
(Updated the code example again ... I realized some typos in the code examples, sorry about that! Now the above full code example it should be working!

**Comment by hbredin** [comment]
Great. Thanks a lot @samuell
