### ISSUE TITLE
Accessing parameters of upstream tasks

### ISSUE THREAD

**Issue by hbredin** [samuell/sciluigi#17]
Say `TaskB` relies on the output of `TaskA`.

```
taskB.in_A = taskA.out_A
```

Is there an easy way to know what parameters were used in `TaskA`, from within `TaskB` ?
Something like `self.in_A().get_params()` ?

**Comment by samuell** [comment]
> Is there an easy way to know what parameters were used in TaskA, from within TaskB ?
Something like self.in_A().get_params() ?

Hi @hbredin !

self.in_A() will return a [sciluigi.TargetInfo](https://github.com/samuell/sciluigi/blob/master/sciluigi/dependencies.py#L12-L30) object, which keeps the upstream task in its `task` field, so you should be able to get the params with: 

```python
self.in_A().task.get_params()
```

Hope this helps!

**Comment by hbredin** [comment]
Just what I needed. Thanks!
