### ISSUE TITLE
Statement of purpose

### ISSUE THREAD

**Issue by averagehat** [samuell/sciluigi#3]
The example in the README does not make it clear what the intention of `sciluigi` is, nor what the benefits would be. I'm interested in this project but would need to know more about its intentions before contributing.

**Comment by samuell** [comment]
Hi @averagehat and thanks for reporting/asking! I will try to add a better description of that in the weekend!

**Comment by samuell** [comment]
@averagehat I have added some basic information about the library now! Hope it helps!

Please see also this collection of links, to materials covering our experiences which lead up to the decision to create SciLuigi: http://bionics.it/posts/our-experiences-using-spotifys-luigi-for-bioinformatics-workflows

I think especially see the talk I gave at eInfraMPS 2015, on pipelineing with Luigi:
- [Slides](http://www.slideshare.net/SamuelLampa/building-workflows-with-spotifys-luigi?qid=8b2118f2-07cb-4480-9aec-6913ce2acb10)
- [Video](https://www.youtube.com/watch?v=f26PqSXZdWM)

Feel free to report if there is any essential information missing!

**Comment by samuell** [comment]
Closing now. Feel free to re-open, if you think more information is needed.
