### ISSUE TITLE
support for parallel_scheduling?

### ISSUE THREAD

**Issue by mjmonroe** [samuell/sciluigi#8]
When I use a luigi.cfg file with parallel_scheduling turned on and run example1.py the log file shows:
```
2015-09-08 13:48:00 |     INFO | --------------------------------------------------------------------------------
2015-09-08 13:48:00 |     INFO | SciLuigi: MyWorkflow Workflow Started
2015-09-08 13:48:00 |     INFO | --------------------------------------------------------------------------------
2015-09-08 13:48:00 |     INFO | Scheduled MyWorkflow(instance_name=sciluigi_workflow) (PENDING)
```
Nothing else happens. It appears that there is a deadlock condition somewhere that prevents MyWorkflow from being scheduled. I have not been able to figure out what the issue is. 

My luigi.cfg file:
```
[core]
parallel_scheduling=True
workers=2
local_scheduler=True
```

**Comment by samuell** [comment]
Many thanks for reporting!

I'll try and see if I get the same result.

Do you have some simple example workflow that has this behavior, or does it happen e.g. for the examples included in the examples folder too?

**Comment by mjmonroe** [comment]
The example1.py that I was referring to is the one in sciluigi's example directory. I also tried the example3_workflow.py, and it did the same thing. If I set parallel_scheduling=False, then it works just fine.

**Comment by samuell** [comment]
Thanks, will check!

**Comment by samuell** [comment]
I'm having my suspicions, but as long as I don't know, let me not speculate too much :)

But what I find so far with some pdb debugging, is that it stops and waits the second time it reaches [this line](https://github.com/spotify/luigi/blob/c3af8269448f560d11c1ad24204fb7a3c024d030/luigi/worker.py#L407) in luigi. 

Hope to find a way to figure out why.

**Comment by samuell** [comment]
@mjmonroe In the meanwhile, while trying to figure this out, I assume you know that parallel scheduling does not speed up the actual execution at all, only the scheduling phase? (As also discussed [here](https://groups.google.com/d/msg/luigi-user/QoephQpYxLg/GcAVXL5-0YwJ)).

Thus, this would be mostly relevant if you have extreme numbers of tasks.

In fact, we have ourselves never thought we needed to speed up the scheduling phase, even though we have hundreds of tasks sometimes. 

But you might have different needs? :)

**Comment by mjmonroe** [comment]
Your right, I do not think I will need to use parallel scheduling, only multiple workers. The thread really helps with the definitions of the two.

**Comment by samuell** [comment]
I will close this as a "won't fix", unless someone finds a way to solve this easily, as for us, this is not a priority, and there seem to be some problems with our approach, making this hard.
